//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation_TO_Rooms
    {
        public int Id { get; set; }
        public int RoomNum { get; set; }
        public int ReservationNum { get; set; }
        public Nullable<int> ReservationId { get; set; }
        public Nullable<int> RoomId { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Room Room { get; set; }
    }
}
